export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const FETCH_TASKS = 'FETCH_TASKS'
export const TOGGLE_EDIT_TASK = 'TOGGLE_EDIT_TASK'
